### ISSUE TITLE
Missing "openipmi" service on Debian 6, 7, 8

### ISSUE THREAD

**Issue by vholer** [jhoblitt/puppet-ipmi#29] opened 2016-07-26 14:05 UTC
Module fails on these systems. This service will be in future stable, which is the far future
https://packages.debian.org/search?suite=stretch&arch=any&mode=path&searchon=contents&keywords=%2Fetc%2Finit.d%2Fopenipmi

**Comment by jschaeff** [comment] 2016-07-29 12:35
As for CentOS 6, there is no such thing a an openipmi service.

Ther should be a condition on the OS version in the module.

**Comment by EpiqSty** [comment] 2017-11-23 15:20
Hi, do you have any news here? 
We are going to use that module in Debian 7&8, but faced with that issue ...

**Comment by jschaeff** [comment] 2017-11-25 14:35
Feel free to use my fork, while the PR or the issue is not treated upstream.

**Comment by EpiqSty** [comment] 2017-11-29 10:45
@jschaeff , thanks we have check it, but seems it not compatible with our puppet 3, we will migrate to puppet 5 and then test it again.

**Comment by rgevaert** [comment] 2018-01-16 10:31
I switched to the fork as on jessie it failed to run...

**Comment by jhoblitt** [comment] 2022-04-08 00:05
The 3.0.0 release drops support for Debian < 8.  I don't have any bare metal debian hosts with a BMC.  Could someone test with the current latest and report if this is still an issue?  #29 never passed CI.

**Comment by jhoblitt** [comment] 2022-04-11 19:18
I'm going to close this as Debian 6 and 7 are obsolete.

**Closed by jhoblitt** 2022-04-11 19:18 UTC
Labels: awaiting feedback
